version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - run:
          name: Print environment versions
          command: |
            NPM_V=$(npm -v)
            echo npm version':' $NPM_V
      - checkout
      - run:
          name: Package Install
          command: |
            npm i
      - run:
          name: build
          command: npm run build -- --rel
      - run:
          name: test
          command: npm test